### PR TITLE
Remove gray styling for private snippets

### PR DESCRIPTION
**Pull request by rileyjshaw**
Addresses #4

### CODE REVIEW

**Comment by rileyjshaw** [comment]
@mroth @csilvers this removes the user-facing distinction between public and private snippets. Thought you'd have thoughts on whether this is something we want to preserve.

**Comment by mroth** [comment]
I don't use the web interface much at all anymore, so I don't have a stake in this game.  Thus far it looks you you are the only person with a private snippet this week @rileyjshaw, so I'd defer to your preference on how it's displayed to others.  @csilvers?

**Comment by csilvers** [comment]
Sorry I didn't see this until now -- I don't typically look for PRs (but use phabricator even for the snippets repo).

I would like there to be some clear notification in the snippets that the snippet is private, so people reading snippets know whether they can talk about that snippet freely with others (outside KA) or not.

I am not at all wedded to that clear notification being gray text.  If you'd like to indicate it in some other way, that's fine by me.

**Comment by rileyjshaw** [comment]
Closing, as https://github.com/Khan/snippets/commit/729cfe8b46aeff019ff6b4b14256c944e0437679 adds new visual tags for private and blank snippets:

screen shot 2015-12-21 at 7 54 31 pm
screen shot 2015-12-21 at 7 54 43 pm

**Pull request closed without merging**
